linters:
    BorderZero:
        enabled: false
    QualifyingElement:
        enabled: false
    DuplicateProperty:
        enabled: false
    PseudoElement:
        enabled: false
    SelectorDepth:
        max_depth: 4
    NestingDepth:
        max_depth: 4
    Indentation:
        width: 4
